### ISSUE TITLE
Error in vaccination data from 2021-09-08

### ISSUE THREAD

**Issue by lucasrodes** [COVID19-Malta/COVID19-Cases#11]
Hi @hugoamuscat @stefanbuttigieg

There seems to be a typo for the last data point reported in the [vaccination dataset.](https://github.com/COVID19-Malta/COVID19-Cases/blob/master/COVID-19%20Malta%20-%20Vaccination%20Data.csv#L236) Specifically in column `Total Vaccination Doses`. The reported number is very low.

Thanks for your help and your work!

**Comment by agiuh001** [comment]
Hi @lucasrodes, thanks for your message. Did you take note of the additional of a new column to account for booster doses?

**Comment by agiuh001** [comment]
Sorry, now realised what you meant... Will correct it straight away. Thanks!

**Comment by lucasrodes** [comment]
Thanks, @agiuh001!

Yes, we recently added the boosters for Malta to our dataset and [charts](https://ourworldindata.org/explorers/coronavirus-data-explorer?zoomToSelection=true&facet=none&pickerSort=asc&pickerMetric=location&Metric=Vaccine+booster+doses&Interval=7-day+rolling+average&Relative+to+Population=true&Align+outbreaks=false&country=~MLT).
