### ISSUE TITLE
Possible typo in vaccinations data

### ISSUE THREAD

**Issue by lucasrodes** [COVID19-Malta/COVID19-Cases#4]
Hi, we are currently relying on your [vaccination data](https://github.com/COVID19-Malta/COVID19-Cases/blob/master/COVID-19%20Malta%20-%20Vaccination%20Data.csv) for our dataset [owid/covid-19-data](https://github.com/owid/covid-19-data) and spotted a possible typo in your data.

If you check the data for 23/01/2021 and 24/01/2021:

Date | Total Vaccination Doses | Second Dose Taken
-- | -- | --
23/01/2021 | 18930 | 0
24/01/2021 | 19981 | 1198

Now, if the field "Second Dose Taken" is correct for 24/01/2021, it seems to me that the field "Total Vaccination Doses" is wrongly reported. Note that the number of total doses on the 23rd + the new number of second doses on the 24th is greater, i.e. 18930 + 1198 = 20128 > 19981.

Maybe you could help us with this? Thanks in advance! Also for tracking this data.

**Comment by stefanbuttigieg** [comment]
Dear @lucasrodes apologies for the delayed response. Our team received the first dataset for second dose on 24/01/2021. Thi s implies that before 24/01/2021 there might have already been second doses given. Moving forward we will work to see whether we can update this data.
