### ISSUE TITLE
Missing population denominator for vaccination quota calculations

### ISSUE THREAD

**Issue by mdebono** [COVID19-Malta/COVID19-Cases#6]
Hi,

The Malta government recently claimed that Malta reached 70% of the population with first doses of vaccine, but there is no mention of the population denominator value for this. If one were to use the population value from the PCR tests data as shown in the README, one would come up with a percentage of ~60%.

There have been suggestions that the claim is based on the adult population, but it is not so clear. Could you point us to an exact value to be used, as is shown for the PCR tests, or to a source for such data?

Some other datasets for vaccinations in other countries include the quotas/percentages of first doses and full doses in their dataset, and would be a welcome addition in Malta's vaccination dataset.

Thanks in advance and regards.

**Comment by hugoamuscat** [comment]
Thank you for your observations and sorry for the delay in replying.  The COVID Public Health Data Management team is only involved in the publication of the numerators, as communicated by personnel in charge of the Vaccination Registration System.
