### ISSUE TITLE
Incorrect total recoveries for 29th August 2020

### ISSUE THREAD

**Issue by frankieinguanez** [COVID19-Malta/COVID19-Cases#7]
According to Sahha on facebook total recoveries is 1244 for 29th August 2020. This repository has it listed at 1224.

**Comment by hugoamuscat** [comment]
Thank you for spotting this typo and alerting us to it.  It has now been corrected.  Apologies for the late response.

**Comment by frankieinguanez** [comment]
You are more than welcome @hugoamuscat , glad to be able to contribute. Well done for this service.
