### ISSUE TITLE
Vaccination data wrong date

### ISSUE THREAD

**Issue by lucasrodes** [COVID19-Malta/COVID19-Cases#9]
Hi,
We have noticed that in file [COVID-19 Malta - Vaccination Data.csv](https://github.com/COVID19-Malta/COVID19-Cases/blob/master/COVID-19%20Malta%20-%20Vaccination%20Data.csv) the entry for 2021-07-25 may have a wrong date assigned:

|Date      |Total Vaccination Doses|Fully vaccinated (2 of 2 or 1 of 1)|Received one dose|
|----------|-----------------------|-----------------------------------|-----------------|
|23/07/2021|742361                 |368587                             |392444           |
|24/07/2021|743712                 |369441                             |392994           |
|25/06/2021|744521                 |370187                             |393062           |

Thanks

**Comment by hugoamuscat** [comment]
Thanks for spotting the typo.  It has been corrected.
